[[QPALM]]
arch = "aarch64"
git-tree-sha1 = "105b8c44d1d28f518d658125848ebab98736b592"
libc = "glibc"
os = "linux"

    [[QPALM.download]]
    sha256 = "b6dafb3a620bfef969a010b03879a844b6ffb49ab7246b52075b98b48901d268"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.aarch64-linux-gnu.tar.gz"
[[QPALM]]
arch = "aarch64"
git-tree-sha1 = "1c409c5d162126c8013865b110572e2b64579cea"
libc = "musl"
os = "linux"

    [[QPALM.download]]
    sha256 = "f39e52ec375860c945a1c91ed49ae7dcf1fe5a3e64111640a929fce5f9c50f6a"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.aarch64-linux-musl.tar.gz"
[[QPALM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ac4669bb5d0631c4206f02a9f0709443bca95fc"
libc = "glibc"
os = "linux"

    [[QPALM.download]]
    sha256 = "c330bb664ef3e46fd1135daea897594add7bc13642fbcec87abf1d903817e04d"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[QPALM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf5ed25855a752044d0ee37ea0db4dda1f413d38"
libc = "musl"
os = "linux"

    [[QPALM.download]]
    sha256 = "94363ee21be927f3d9fafb8dd90c7fde945f2f705a1508fad04abf2d054e7aaf"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[QPALM]]
arch = "i686"
git-tree-sha1 = "bc2d73a50226c07c7d463beca158683c37589e04"
libc = "glibc"
os = "linux"

    [[QPALM.download]]
    sha256 = "a0cfc4c93e286a48557112f3074f19ec7772f1a801ea7f0b811963a184427b2e"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.i686-linux-gnu.tar.gz"
[[QPALM]]
arch = "i686"
git-tree-sha1 = "5a5878f54bf4a820c6254ab9d52a7685e37b6b96"
libc = "musl"
os = "linux"

    [[QPALM.download]]
    sha256 = "0b68d21358878d415200c6c7d322be285251db64fb52f32f2f8607c0ad468f9d"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.i686-linux-musl.tar.gz"
[[QPALM]]
arch = "i686"
git-tree-sha1 = "77284f6703e70220753120de664e1f2293df9984"
os = "windows"

    [[QPALM.download]]
    sha256 = "dc31c87a5946d547e591f67c6c9043489afd4a731a27985ce4de10940d04f714"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.i686-w64-mingw32.tar.gz"
[[QPALM]]
arch = "powerpc64le"
git-tree-sha1 = "98d08d35b23bef8ba1064b49f056221a265ae24e"
libc = "glibc"
os = "linux"

    [[QPALM.download]]
    sha256 = "d1813c43d81212da1e59629e84c19e1cf40186af81d53fef44a03a667a671b35"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[QPALM]]
arch = "x86_64"
git-tree-sha1 = "ea43e48e04a4cb78abfec85317f181c71abadffd"
os = "macos"

    [[QPALM.download]]
    sha256 = "5d9fa77f8b6a344f1b0ae43aa9ae89bb19c8c092b2e398dd974b6c2a01c9cd06"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.x86_64-apple-darwin.tar.gz"
[[QPALM]]
arch = "x86_64"
git-tree-sha1 = "251fe4fb97bea951c79353e3225a16c9a9360444"
libc = "glibc"
os = "linux"

    [[QPALM.download]]
    sha256 = "b8b27f131c429b9f544e8d5198bf7fe0e43e13889fe00bf60c39acdebee4dea4"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.x86_64-linux-gnu.tar.gz"
[[QPALM]]
arch = "x86_64"
git-tree-sha1 = "3d2f291847884329eaf0d4a0fe5607c83eb35def"
libc = "musl"
os = "linux"

    [[QPALM.download]]
    sha256 = "f13e6b977dd7492fb730ef381a42390ed4b506b160051c0496f75c191cb2b703"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.x86_64-linux-musl.tar.gz"
[[QPALM]]
arch = "x86_64"
git-tree-sha1 = "c98da7c55f9953bc9117482b65e100b6a2c705bb"
os = "freebsd"

    [[QPALM.download]]
    sha256 = "cc32831b1ea4a5232df1748ba5f56cb6c8d1ccd80f030212a0328fdd3827841a"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[QPALM]]
arch = "x86_64"
git-tree-sha1 = "e5429c1b6323563d380d09942a9223048e60948b"
os = "windows"

    [[QPALM.download]]
    sha256 = "71a7670d72ff68417f3118e7a1dd9926c74bb804aec82af68b33f90725422eeb"
    url = "https://github.com/JuliaBinaryWrappers/QPALM_jll.jl/releases/download/QPALM-v0.3.0+0/QPALM.v0.3.0.x86_64-w64-mingw32.tar.gz"
