# Autogenerated wrapper script for QPALM_jll for x86_64-apple-darwin
export libqpalm_jll

JLLWrappers.@generate_wrapper_header("QPALM")
JLLWrappers.@declare_library_product(libqpalm_jll, "@rpath/libqpalm_jll.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libqpalm_jll,
        "lib/libqpalm_jll.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
